default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  port: <%= ENV['DB_PORT'] %>
  host: <%= ENV['DB_HOST'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['DB_NAME'] %>

test:
  <<: *default
  database: cep_lookup_api_test

production:
  <<: *default
  database: cep_lookup_api_production
  username: cep_lookup_api
  password: <%= ENV['CEP_LOOKUP_API_DATABASE_PASSWORD'] %>